version: '3.1'

services:
  microservice:
    build: ./
    env_file: ./.env
    ports:
      - '$APP_PORT:$APP_PORT'
    links:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    restart: on-failure
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    volumes:
      - /data/db:/data/db
